---
name: "Workflow call: Lint"

on:
  workflow_call:

jobs:
  pre-commit-check:
    name: Check pre-commit rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --config .pre-commit-config.yaml

  lint-yaml:
    name: Lint Yaml Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 1

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: shell
          filters: |
            yaml:
              - added|modified: "**.yaml"
              - added|modified: "**.yml"

      - name: "Yamllint"
        if: ${{ steps.filter.outputs.yaml == 'true' }}
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: "${{ steps.filter.outputs.yaml_files }}"
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: .ci/lint/yamllint.yaml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  metadata-validation:
    name: Validate Image Metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: shell
          filters: |
            cue:
              - added|modified: "apps/**/metadata.yaml"
              - added|modified: ".ci/lint/metadata.rules.cue"

      - name: Setup CUE
        if: ${{ steps.filter.outputs.cue == 'true' }}
        uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1

      - name: Validate image metadata
        if: ${{ steps.filter.outputs.cue == 'true' }}
        shell: bash
        # Run against all files to ensure they are tested if the cue schema is changed.
        run: |
          find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./.ci/lint/metadata.rules.cue

  renovate-config-validator:
    name: Validate Renovate Config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: filter
        with:
          list-files: shell
          filters: |
            renovate:
              - added|modified: ".github/renovate.json5"

      - name: Validate Renovate Config
        if: ${{ steps.filter.outputs.renovate == 'true' }}
        uses: rinchsan/renovate-config-validator@a12a2b98cd4db923c33d1ce407c57afb43f3ff59 # v0.2.0
        with:
          pattern: ".github/renovate.json5"
